import DS from 'ember-data';

export default DS.Model.extend({
  idMunicipio: DS.attr(),
  idProprietario: DS.attr(),
  idTecnico: DS.attr(),
  nome: DS.attr(),
  codEmater: DS.attr(),
  codCar: DS.attr(),
  cnpj: DS.attr(),
  historico: DS.attr(),
  imagemDestaque: DS.attr(),
  variedade: DS.attr(),
  especies: DS.attr(),
  espacamento: DS.attr(),
  propriedadeCertificada: DS.attr(),
  site: DS.attr(),
  facebook: DS.attr(),
  area: DS.attr(),
  exibirArea: DS.attr(),
  anoPlantio: DS.attr(),
  exibirAnoPlantio: DS.attr(),
  areaCafe: DS.attr(),
  exibirAreaCafe: DS.attr(),
  areaPreservacao: DS.attr(),
  exibirAreaPreservacao: DS.attr(),
  producao: DS.attr(),
  exibirProducao: DS.attr(),
  produtividade: DS.attr(),
  exibirProdutividade: DS.attr(),
  nomeProprietario: DS.attr(),
  exibirNomeProprietario: DS.attr(),
  emailProprietario: DS.attr(),
  exibirEmailProprietario: DS.attr(),
  telefoneProprietario: DS.attr(),
  exibirTelefoneProprietario: DS.attr(),
  perfilPublico: DS.attr(),
  liberado: DS.attr(),
  publicado: DS.attr(),
  edicaoProprietario: DS.attr(),
  alteracoesProprietario: DS.attr(),
  latitude: DS.attr(),
  longitude: DS.attr(),

  //Relations
  municipio: DS.belongsTo('municipio'),
});
